FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
# Next.js bakes NEXT_PUBLIC_* variables at build time. Allow providing them via build args.
ARG NEXT_PUBLIC_AUTH_PROVIDER=zitadel
ARG NEXT_PUBLIC_ZITADEL_AUTHORITY=https://idp.beyond-bot.ch
ARG NEXT_PUBLIC_ZITADEL_CLIENT_ID=363202201499207860
ARG NEXT_PUBLIC_ZITADEL_SCOPES="openid profile email"
ARG NEXT_PUBLIC_ZITADEL_RESOURCE
ARG NEXT_PUBLIC_AUTH0_DOMAIN
ARG NEXT_PUBLIC_AUTH0_CLIENT_ID
ARG NEXT_PUBLIC_AUTH0_AUDIENCE
ARG NEXT_PUBLIC_SYNAPSE_URL
ARG LANGGRAPH_API_URL
ARG MAIN_API_URL
ARG STRIPE_SECRET_KEY
ARG BBOT_DEFAULT_RESPONSE_MODEL=infomaniak/moonshotai/Kimi-K2.5
ARG INFOMANIAK_PRODUCT_ID=107316
ARG BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL
ENV NEXT_PUBLIC_AUTH_PROVIDER=${NEXT_PUBLIC_AUTH_PROVIDER}
ENV NEXT_PUBLIC_ZITADEL_AUTHORITY=${NEXT_PUBLIC_ZITADEL_AUTHORITY}
ENV NEXT_PUBLIC_ZITADEL_CLIENT_ID=${NEXT_PUBLIC_ZITADEL_CLIENT_ID}
ENV NEXT_PUBLIC_ZITADEL_SCOPES=${NEXT_PUBLIC_ZITADEL_SCOPES}
ENV NEXT_PUBLIC_ZITADEL_RESOURCE=${NEXT_PUBLIC_ZITADEL_RESOURCE}
ENV NEXT_PUBLIC_AUTH0_DOMAIN=${NEXT_PUBLIC_AUTH0_DOMAIN}
ENV NEXT_PUBLIC_AUTH0_CLIENT_ID=${NEXT_PUBLIC_AUTH0_CLIENT_ID}
ENV NEXT_PUBLIC_AUTH0_AUDIENCE=${NEXT_PUBLIC_AUTH0_AUDIENCE}
ENV NEXT_PUBLIC_SYNAPSE_URL=${NEXT_PUBLIC_SYNAPSE_URL}
ENV LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
ENV MAIN_API_URL=${MAIN_API_URL}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV BBOT_DEFAULT_RESPONSE_MODEL=${BBOT_DEFAULT_RESPONSE_MODEL}
ENV INFOMANIAK_PRODUCT_ID=${INFOMANIAK_PRODUCT_ID}
ENV BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL=${BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL}
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME=0.0.0.0
ARG BBOT_DEFAULT_RESPONSE_MODEL=infomaniak/moonshotai/Kimi-K2.5
ARG INFOMANIAK_PRODUCT_ID=107316
ARG BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL
ENV BBOT_DEFAULT_RESPONSE_MODEL=${BBOT_DEFAULT_RESPONSE_MODEL}
ENV INFOMANIAK_PRODUCT_ID=${INFOMANIAK_PRODUCT_ID}
ENV BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL=${BBOT_DEFAULT_RESPONSE_MODEL_BASE_URL}

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

# OpenShift runs the container with an arbitrary UID; make /app writable for that UID's group (0).
RUN chgrp -R 0 /app && chmod -R g=u /app

EXPOSE 8080
CMD ["node_modules/.bin/next", "start", "-p", "8080"]
